### ISSUE TITLE
Highlighting consufused by !

### ISSUE THREAD

**Issue by aeschli** [microsoft/TypeScript-TmLanguage#746] opened 2019-05-02 08:56 UTC
The following JavaScript code snipped is not correctly parsed. Looks like the `!` in front of `function` confuses.

```js
	switch (location.hash) {
		case "#stub":
			!function () { var c = window, t = document, n = function () { if (!c.frames.__cmpLocator) if (t.body) { var a = t.body, e = t.createElement("iframe"); e.style.cssText = "display:none", e.name = "__cmpLocator", a.appendChild(e) } else setTimeout(n, 5) }; n(); var a = function (t) { var n = "string" == typeof t.data; try { var a = n ? JSON.parse(t.data) : t.data; if (a.__cmpCall) { var p = a.__cmpCall; c.__cmp(p.command, p.parameter, function (a, e) { var c = { __cmpReturn: { returnValue: a, success: e, callId: p.callId } }; t.source.postMessage(n ? JSON.stringify(c) : c, "*") }) } } catch (a) { } }; "function" != typeof __cmp && (c.__cmp = function () { var a = arguments; if (__cmp.a = __cmp.a || [], !a.length) return __cmp.a; "ping" === a[0] ? a[2]({ gdprAppliesGlobally: !1, cmpLoaded: !1 }, !0) : __cmp.a.push([].slice.apply(a)) }, __cmp.msgHandler = a, c.addEventListener("message", a, !1)) }();
			console.log("Using standard freestanding stub.");
			break;
		case "#stubdbg":
			!function () { var c = window, t = document, n = function () { if (!c.frames.__cmpLocator) if (t.body) { var a = t.body, e = t.createElement("iframe"); e.style.cssText = "display:none", e.name = "__cmpLocator", a.appendChild(e) } else setTimeout(n, 5) }; n(); var a = function (t) { var n = "string" == typeof t.data; try { var a = n ? JSON.parse(t.data) : t.data; if (a.__cmpCall) { var p = a.__cmpCall; c.__cmp(p.command, p.parameter, function (a, e) { var c = { __cmpReturn: { HandledByStub: true, returnValue: a, success: e, callId: p.callId } }; t.source.postMessage(n ? JSON.stringify(c) : c, "*") }) } } catch (a) { } }; "function" != typeof __cmp && (c.__cmp = function () { var a = arguments; if (__cmp.a = __cmp.a || [], !a.length) return __cmp.a; console.log('Stub queueing __cmp( "' + a[0] + '", ' + a[1] + ' )'); "ping" === a[0] ? a[2]({ gdprAppliesGlobally: !1, cmpLoaded: !1 }, !0) : __cmp.a.push([].slice.apply(a)) }, __cmp.msgHandler = a, c.addEventListener("message", a, !1)) }();
			console.log("Using 'debug' freestanding stub.");
			break;
		default:
			console.log("Using no freestanding stub.");
			break;
	}
```

**Comment by sheetalkamat** [comment] 2019-05-02 17:54
Seems to work::
![image](https://user-images.githubusercontent.com/8052792/57095830-a93b3700-6cc8-11e9-8cbd-d93ec539f1f2.png)

**Comment by KamasamaK** [comment] 2019-05-03 06:00
The coloring of the example content happens to be fine, but the scoping is wrong and causes issues with subsequent code. I did not find that the `!` was the cause, though. Oddly enough, it seems that spacing actually affects it. I tried to format the sample code to be a bit more sane and readable to more easily find where it was breaking, and found the following in that process.

From the following partially formatted code
```js
switch (location.hash) {
	case "#stub":
		!function () {
			var c = window,
				t = document,
				n = function () {
					if (!c.frames.__cmpLocator)
						if (t.body) {
							var a = t.body, e = t.createElement("iframe");
							e.style.cssText = "display:none", e.name = "__cmpLocator", a.appendChild(e)
						} else setTimeout(n, 5)
				}; 
				n(); 
				var a = function (t) { 
					var n = "string" == typeof t.data; 
					try { 
						var a = n ? JSON.parse(t.data) : t.data; 
						if (a.__cmpCall) { 
							var p = a.__cmpCall; 
							c.__cmp(p.command, p.parameter, function (a, e) { 
								var c = { 
									__cmpReturn: { 
										returnValue: a, success: e, callId: p.callId 
									} 
								}; 
								t.source.postMessage(n ? JSON.stringify(c) : c, "*") }) 
						} } catch (a) { } }; "function" != typeof __cmp && (c.__cmp = function () { var a = arguments; if (__cmp.a = __cmp.a || [], !a.length) return __cmp.a; "ping" === a[0] ? a[2]({ gdprAppliesGlobally: !1, cmpLoaded: !1 }, !0) : __cmp.a.push([].slice.apply(a)) }, __cmp.msgHandler = a, c.addEventListener("message", a, !1))
		}();
		console.log("Using standard freestanding stub.");
		break;
	default:
		console.log("Using no freestanding stub.");
		break;
}
```

I get
![image](https://user-images.githubusercontent.com/22951521/57121468-bfd3a380-6d45-11e9-9002-3d6520c1c2ff.png)
with the cursor at the beginning of line 29, which is incorrect.

If a new line is added to line 27 between the first two closing braces, the following unexpectedly happens
![image](https://user-images.githubusercontent.com/22951521/57121544-4daf8e80-6d46-11e9-9d07-d13a1906de7c.png)
with the cursor now at the beginning of line 30 to account for the new line, which appears to now be correct.

**Comment by sheetalkamat** [comment] 2019-07-11 21:39
Again this is no repro:
```
>		console.log("Using standard freestanding stub.");
 ^^
 source.ts switch-statement.expr.ts switch-block.expr.ts

>		console.log("Using no freestanding stub.");
 ^^
 source.ts switch-statement.expr.ts switch-block.expr.ts
```

**Closed by sheetalkamat** 2019-07-11 21:39 UTC

**Comment by KamasamaK** [comment] 2019-07-11 22:28
I just tried the above example again and can verify that it is fixed.
