### ISSUE TITLE
Install Error - Couldn't find a compatible version of Latest TypeScript and Javascript Grammar with this version of Code

### ISSUE THREAD

**Issue by 4kochi** [Microsoft/TypeScript-TmLanguage#275] opened 2016-09-29 09:41 UTC
`Couldn't find a compatible version of Latest TypeScript and Javascript Grammar with this version of Code.: Error: Couldn't find a compatible version of Latest TypeScript and Javascript Grammar with this version of Code.,    at e.getLastValidExtensionVersionReccursively (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:9:21161),    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:9:21536,    at Object.m [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:23338),    at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:26916),    at _run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:28744),    at _completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:28185),    at Object.m [as _notify] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:23338),    at Object.enter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:26916),    at _run (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:28744),    at _completed (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/node/sharedProcessMain.js:5:28185)`

Version 1.6.0-insider (1.6.0-insider) 
Commit Hash 6746e53a611ecb3e0777fca6a4c8387dc392513f

Mac OSX Sierra (macOS 10.12 (16A323))

Use setting `"typescript.tsdk"` with TypeScript 2.0.3 installed globally.

**Comment by joaomoreno** [comment] 2016-10-04 15:43
Duplicate of Microsoft/vscode#12985

**Closed** 2016-10-04 17:40 UTC
Labels: bug, duplicate
