### ISSUE TITLE
Broken colorization in multiline generic parameters

### ISSUE THREAD

**Issue by infctr** [Microsoft/TypeScript-TmLanguage#745] opened 2019-04-28 13:28 UTC
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.50 / latest

**Code**

```ts
interface Static {
  path<
    T1 extends string,
    T2 extends string,
    T3 extends string,
    T4 extends string,
    T5 extends string,
    TResult
  >(
    path: [T1, T2, T3, T4, T5],
    obj: { [K1 in T1]: { [K2 in T2]: { [K3 in T3]: { [K4 in T4]: { [K5 in T5]: TResult } } } } }
  ): TResult;
}

```

![image](https://user-images.githubusercontent.com/15550153/56865088-a0015000-69d2-11e9-9ef7-4884967cf73a.png)

```sh
❯ code-insiders -v
1.34.0-insider
56f1b4795fed05677eb82a21dac4fc1ab62d747b
x64
```

**Comment by sheetalkamat** [comment] 2019-04-29 01:41
Duplicate of #479

**Closed by sheetalkamat** 2019-04-29 01:41 UTC
