### ISSUE TITLE
Broken highlighting in objects in function parameters after type declaration without a semicolon

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/TypeScript-TmLanguage#834] opened 2020-06-30 18:15 UTC
**VSCode Version**: 1.46.1

**Code:**
```ts
type n = number
console.log(0, { what: true })
```

For some reason the `true` is not colored.

![image](https://user-images.githubusercontent.com/26556598/86161614-2b65fc00-bb16-11ea-9ab5-88c035804474.png)

More weird examples:
![image](https://user-images.githubusercontent.com/26556598/86161956-b9da7d80-bb16-11ea-8d46-ad4776ba19b5.png)

**Comment by sheetalkamat** [comment] 2020-11-05 21:09
This is working as intended because of limitation of textmate grammar rules which doesn't allow lookup beyond line. Duplicate of #352

**Closed by sheetalkamat** 2020-11-05 21:09 UTC
