### ISSUE TITLE
5.0.20221116 versions

### ISSUE THREAD

**Issue by Tom-fl** [microsoft/TypeScript-TmLanguage#938] opened 2022-11-17 10:24 UTC
Code highlighting failed

**Comment by moataz9** [comment] 2022-11-17 12:04
yeah, after i disabled it the ts & js highlighting is  back

**Comment by Rafat97** [comment] 2022-11-17 15:04
https://github.com/microsoft/TypeScript-TmLanguage/issues/937

may be same problem

**Comment by juparog** [comment] 2022-11-17 15:39
error with code highlighting

![image](https://user-images.githubusercontent.com/58745412/202490652-d9e164de-dc81-4f87-806c-2d3697e4aeae.png)

![image](https://user-images.githubusercontent.com/58745412/202490722-4a525793-854d-4583-9ab2-4488f68d7bc1.png)

**Comment by vssoares** [comment] 2022-11-17 16:43
You can switch to previous version
![Screenshot_1](https://user-images.githubusercontent.com/45067354/202505650-b3e6e07a-826d-4f6b-a6cd-47ad95397570.png)

**Comment by sheetalkamat** [comment] 2022-11-17 19:47
Duplicate of https://github.com/microsoft/vscode-typescript-next/issues/43

**Closed by sheetalkamat** 2022-11-17 19:47 UTC
