### ISSUE TITLE
highlighting regression in latest extension [VS Code]

### ISSUE THREAD

**Issue by wprater** [Microsoft/TypeScript-TmLanguage#323] opened 2016-10-19 16:19 UTC
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.4 / latest

**Code**

```ts
(true ? foo() : bar.then(() => {
});

// breaks coloring below
const baz = 'nope';
```

**Comment by sheetalkamat** [comment] 2016-10-19 17:44
Duplicate of #321

**Closed by sheetalkamat** 2016-10-19 17:44 UTC
Labels: bug, duplicate
