### ISSUE TITLE
Syntax highlighting fails when concatenating strings across a newline with a space between the + and newline

### ISSUE THREAD

**Issue by jackhorton** [Microsoft/TypeScript-TmLanguage#652] opened 2018-08-20 16:25 UTC
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.43 / latest

**Code**

![image](https://user-images.githubusercontent.com/4370013/44325034-5ce6ea00-a40c-11e8-86dd-77fbffc5e5b2.png)

(note that I have whitespace on -- the trialing space in the failure case is important)

**Comment by sheetalkamat** [comment] 2018-08-21 19:39
Duplicate of #654

**Closed** 2018-08-21 19:40 UTC
