### ISSUE TITLE
TypeScript interface objects properties highlighting glitch

### ISSUE THREAD

**Issue by artaommahe** [Microsoft/TypeScript-TmLanguage#284] opened 2016-09-30 12:48 UTC
VS Code
Version 1.5.1
Commit 07d663dc1bd848161edf4cd4ce30cce410d3d877
Date 2016-09-08T21:34:58.760Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

Latest TypeScript and Javascript Grammar 0.0.2

OS Version: Ubuntu 14.04.4 LTS

Interface's object properties have wrong color

![_871](https://cloud.githubusercontent.com/assets/1944061/18992095/11c6f6d8-8725-11e6-8fdc-33bd820cf3d8.png)

**Comment by sheetalkamat** [comment] 2016-09-30 17:33
This is duplicate of #173 and tracked in Microsoft/vscode##13046

**Closed by sheetalkamat** 2016-09-30 17:33 UTC
Labels: duplicate
