### ISSUE TITLE
Incorrect syntax highlight of async on arrow functions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#226] opened 2016-08-02 08:28 UTC
_From @hh10k on July 30, 2016 13:4_

- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Within a .js or .ts file, add an async lambda function like `async () => {}`
2. Observe that the `async` does not have the expected keyword color, as it would when used before function():

![asyncsyntaxhighlight](https://cloud.githubusercontent.com/assets/2985923/17270580/33e813ae-5698-11e6-9cbb-0e7a6503ed76.png)

_Copied from original issue: Microsoft/vscode#9976_

**Comment by glen-84** [comment] 2016-08-07 21:07
Duplicate of #172 and #168.

**Comment by sheetalkamat** [comment] 2016-09-16 20:55
Fixed by #257

**Closed by sheetalkamat** 2016-09-16 20:55 UTC
