### ISSUE TITLE
`of` not colorized in `for..of` loops

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript-TmLanguage#286] opened 2016-10-01 07:25 UTC
![image](https://cloud.githubusercontent.com/assets/8000722/19012534/96ac3708-876d-11e6-8e3e-5bf0a1319465.png)

**Comment by sheetalkamat** [comment] 2016-10-03 17:36
The root cause of this is Microsoft/vscode#13033 
Closing it here.

**Closed by sheetalkamat** 2016-10-03 17:36 UTC
