### ISSUE TITLE
Incorrect highlight of dynamic import in the TypeScript React syntax

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/TypeScript-TmLanguage#489] opened 2017-07-22 11:53 UTC
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

#### Incorrect highlighting

```tsx
import('preact').then(({ h, render }) => {
	const rootEl = document.getElementById('root');

	render(
		(<div>123</div>),
		rootEl as HTMLElement
	);
});
```

![app tsx service-sb-analyzer 2017-07-22 14-46-56](https://user-images.githubusercontent.com/7034281/28490870-2e52b5ac-6eed-11e7-9a01-062e42ae79cf.png)

#### Correct highlighting

```tsx
const preactLoader = import('preact');

preactLoader.then(({ h, render }) => {
	const rootEl = document.getElementById('root');

	render(
		(<div>123</div>),
		rootEl as HTMLElement
	);
});
```

![app tsx service-sb-analyzer 2017-07-22 14-46-41](https://user-images.githubusercontent.com/7034281/28490871-334f3fd0-6eed-11e7-9d2c-6a72394cc0f4.png)

**Comment by sheetalkamat** [comment] 2017-09-13 23:23
Duplicate of #506 and fixed by 96c7b242918309832e844d08b433d9b5b34eb429

**Closed by sheetalkamat** 2017-09-13 23:23 UTC
