### ISSUE TITLE
Incorrect highlighting after "declare"

### ISSUE THREAD

**Issue by breck7** [Microsoft/TypeScript-TmLanguage#731] opened 2019-03-14 13:39 UTC
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.49 / latest

Expected: console.log(2) to be in blue.
Actual: console.log(2) is in green.

Looks like the "meta.type.declaration.ts" context is not getting popped off the context stack by all patterns.

**Code**

```ts
console.log(1)
declare type scope = string
console.log(2)
function a() {}
console.log(3)
```

![image](https://user-images.githubusercontent.com/74692/54361175-dbbba280-463c-11e9-9a0b-f06b764b6c13.png)

**Comment by breck7** [comment] 2019-03-14 13:41
Funny, after posting that it looks like there's the same bug in the GitHub highlighter too! Perhaps I'm misunderstanding something about the TS syntax and it is user error.

**Comment by sheetalkamat** [comment] 2019-03-14 16:37
Duplicate of  #352 and limitation of textmate grammar syntax

**Closed by sheetalkamat** 2019-03-14 16:37 UTC
