### ISSUE TITLE
Rendering of code broken after using `require.resolve` in the code

### ISSUE THREAD

**Issue by meeroslav** [microsoft/TypeScript-TmLanguage#949] opened 2022-12-13 09:17 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1 (also 1.74.0 and previous versions)
- OS Version: macOS Monterey 12.3

Steps to Reproduce:

1. Clone `https://github.com/nrwl/nx/`
2. Open `packages/nx/src/utils/package-json.ts`
3. Scroll to line 128

Current behavior:
The function call to `require.resolve` is marked with red parenthesis despite no error existing (nor being shown) and all the code after that line has broken visual representation.

Expected behavior:
Code should still maintain the proper theme in files that contain `require.resolve`

![Screenshot 2022-12-13 at 10 17 01](https://user-images.githubusercontent.com/881612/207276986-5b316ba1-2d4f-4325-b78c-08fa799a3fb4.png)

**Comment by mjbvz** [comment] 2022-12-13 19:29
Minimal example:

```ts

export interface PackageJson {
    exports?:
    | string
    | Record<
        string,
        string | { types?: string; require?: string; import?: string }
    >;
}

export function foo() { }
```

**Comment by sheetalkamat** [comment] 2023-02-08 23:31
This is limitation of grammar because there is no way to look beyond or before single line types do not cross line so at the end of string type scope ends and everything beyond will  be expression. Moving  `|` on same line will help with the continuation of the scope.

**Comment by sheetalkamat** [comment] 2023-02-08 23:31
Duplicate of #761

**Closed** 2023-02-08 23:37 UTC
Labels: duplicate, limitation
