### ISSUE TITLE
Highlight error for function named 'is'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#229] opened 2016-08-02 18:41 UTC
_From @unional on July 14, 2016 22:48_

- VSCode Version: 1.3.1
- tsc: 2.0.0
- OS Version: Windows 2012 R2

![image](https://cloud.githubusercontent.com/assets/3254987/16858260/87ce8f04-49da-11e6-9a26-50f3169d594f.png)

_Copied from original issue: Microsoft/vscode#9307_

**Comment by sheetalkamat** [comment] 2016-09-06 21:47
Duplicate of #212

**Closed** 2016-09-16 20:49 UTC
Labels: duplicate
