### ISSUE TITLE
Better syntax highlighting

### ISSUE THREAD

**Issue by octref** [Microsoft/TypeScript-TmLanguage#273] opened 2016-09-29 05:47 UTC
Previously:

![image](https://cloud.githubusercontent.com/assets/4033249/18942299/d6954cda-85cc-11e6-86e8-1ef158fdb1bd.png)

Now:

![image](https://cloud.githubusercontent.com/assets/4033249/18942303/de5d287a-85cc-11e6-8187-521a124190c4.png)

- `this` should have distinctive color.
- keywords like `super`, `instanceof`, `typeof` should have proper highlighting.
- Would be great if I can tell class/interface/const from each other by color too, currently: 
  ![image](https://cloud.githubusercontent.com/assets/4033249/18942375/683fcfc0-85cd-11e6-86c1-0b5197601e5b.png)

**Comment by octref** [comment] 2016-09-29 05:48
Another thing is it would be great to  have some special highlighting for built-ins like `document` and `console`.

**Comment by octref** [comment] 2016-09-29 05:51
OK, something else...

Previously I could at least tell primitives from other constructs, and have a nested object displayed fine...

![image](https://cloud.githubusercontent.com/assets/4033249/18942421/cc71fbbc-85cd-11e6-8360-7941b205d591.png)

Now this looks terrible:

![image](https://cloud.githubusercontent.com/assets/4033249/18942434/e46284c6-85cd-11e6-9109-3600f6bdfd9e.png)

**Comment by Jmclerck** [comment] 2016-09-29 08:16
My syntax highlighting for JavaScript vanished completely after installing this plugin, my Color Theme is set to `Dark+ (default dark)`, previously it looked like this:

![screen shot 2016-09-29 at 09 05 21 3](https://cloud.githubusercontent.com/assets/1395919/18945894/6f067924-8624-11e6-8910-c4ec0a86655f.png)

After installing this plugin in everything was white:

![screen shot 2016-09-29 at 09 05 00 3](https://cloud.githubusercontent.com/assets/1395919/18946009/eeb66814-8624-11e6-8d75-e15cb3062e42.png)

I notice now that this repo only mentions TypeScript but the [tweet](https://twitter.com/code/status/781198942578941953) here suggested JavaScript improvements too, either way, if this is only TypeScript it shouldn't really cause issues with other languages?

**Comment by sheetalkamat** [comment] 2016-09-29 20:41
@octref Thank you for trying out the grammar and reporting the issues.

Most of the issues are theme related rather than issue with grammar and i will file those in Microsoft/vscode repo and reference this back.

```this``` and ```super``` are scoped as ```variable.language``` but they aren't colorized correctly by the theme.

```instanceof```, ```typeof``` are scoped as ```keyword.operator``` and not colorized again the issue with the theme.

I am already talking to vscode folks about the color of typeliteral as part of #173 but I will file a bug just to make sure we are tracking it.

```document``` and ```console``` are scoped correctly, its the theme that needs to handle it.

**Comment by sheetalkamat** [comment] 2016-09-29 20:43
@Jmclerck Can you please provide more information of other extensions installed, vscode version etc so we can investigate this further? I am going to move your issue into separate one just to make sure we are tracking it correctly.

**Comment by octref** [comment] 2016-09-29 21:01
@sheetalkamat Thanks. But as this grammar won't make it to Sep release, I think it'd be better if you can modify the stock theme a bit so it works with well with the grammar, and publish it to marketplace.

Also, Sep release will allow extensions to specify depdendencies -- maybe you can add the theme as a dep for the grammar.

Otherwise it'd be a really bad experiences for users.

**Comment by sheetalkamat** [comment] 2016-09-29 21:14
@octref I have raised vscode theme bugs to track this and will let bug owner decide how to approach this.
Sorry I don't know if I can help much since the issue isn't in the grammar.

**Comment by sheetalkamat** [comment] 2016-09-29 21:44
Closing this issue as there are vscode issues to track the underlying issues

**Closed by sheetalkamat** 2016-09-29 21:44 UTC
Labels: bug

**Comment by octref** [comment] 2016-09-29 22:31
@sheetalkamat
I'll give it a try to see if I can build a theme.
Is there a fast way to know the type of each token (like `this` is `variable.language`)?

Inspecting the css is really slow...
![image](https://cloud.githubusercontent.com/assets/4033249/18974702/b274c686-8659-11e6-9054-1bed38b95d16.png)

**Comment by sheetalkamat** [comment] 2016-09-29 22:57
@octref you could use our test framework

- Clone this repo
- cd build
- npm install
- cd ../test
- npm install
- Add your required code say in cases\test.ts 
- npm test
- It would generate a file called generated\test.baseline.txt, It would have the scopes for the whole file
