### ISSUE TITLE
type declaration causes wrong highlighting in following line

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript-TmLanguage#848] opened 2021-01-20 10:34 UTC
VScode 1.52.1
TS 4.2.0-dev.20210119 & 4.1.3

```ts
type foo = string;
window = window;
```

<img width="123" alt="Code_2021-01-20_11-29-28" src="https://user-images.githubusercontent.com/30108880/105162816-6318ad80-5b13-11eb-9d5a-c8d0a4e0db86.png">
<img width="130" alt="Code_2021-01-20_11-29-24" src="https://user-images.githubusercontent.com/30108880/105162817-63b14400-5b13-11eb-8f3a-61e99ef13c7b.png">

**Comment by sheetalkamat** [comment] 2021-01-20 18:17
This is working as intended because of limitation of textmate grammar rules which doesn't allow lookup beyond line. Duplicate of #352

**Closed by sheetalkamat** 2021-01-20 18:17 UTC
