### ISSUE TITLE
.tsx comment issue using <CTR-/> 

### ISSUE THREAD

**Issue by laminekalinko2** [microsoft/TypeScript-TmLanguage#618] opened 2018-05-28 07:16 UTC
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.41 / latest

**Code**

```ts
// Please include a code snippet that demonstrates the issue
When I run <CTR-/> on .tsx files I get Javascript comment
<code>
// <a href="get_in_touch.html">Get In Touch</a>

</code>

instead of

<code>
{/* <a href="get_in_touch.html">Get In Touch</a> */}
</code>

NB: Im using the latest vscode on ubuntu 

```

**Comment by sheetalkamat** [comment] 2018-05-29 18:41
Please file this issue in https://github.com/Microsoft/vscode repo since this is used only to support the grammar for colorization

**Comment by uloco** [comment] 2019-03-19 09:10
After disabling this plugin, the commenting works again in vscode. I don't know but I think this has to be a bug in this extension somehow. Even tried in vscode insiders, there is no problem in vscode with commenting jsx or tsx on the lastest insider and normal version without this plugin installed. Just try out yourself, install insiders without any extensions, install this extension and tsx commenting stops working correctly.
![vscode-bug-tsx-commenting](https://user-images.githubusercontent.com/8818340/54593560-1d7a8d80-4a2f-11e9-8916-d6896cbeb91c.gif)

**Comment by uloco** [comment] 2019-04-02 18:35
After posting this issue on the official vscode repository, they pointed out, that this has to be fixed in this extension. See: https://github.com/Microsoft/vscode/issues/71586

**Comment by sheetalkamat** [comment] 2019-04-03 19:55
@mjbvz The package is for the beta version of tmLanguage syntax from this repo. Whats the special work that's needed? Intention of the extension is to just make sure coloring is right with the syntax from this repo and get early feedback from users on the changes.

**Comment by mjbvz** [comment] 2019-04-05 00:29
Since this extension contributes a grammar, I think it also needs to set the `embeddedLangauges` field for `jsx-tags`: https://github.com/Microsoft/vscode/blob/master/extensions/typescript-basics/package.json#L68

I've pulled in the latest grammar to VS Code but have not been able to reproduce this issue using our builtin contributions

**Comment by nt4f04uNd** [comment] 2019-06-28 21:42
Why don't you fix this? I still got this issue

**Comment by zedd3v** [comment] 2020-09-09 18:06
Any updates on this ?

**Comment by nt4f04uNd** [comment] 2020-09-09 18:12
@zedd3v as a workaround just don't install this extension, idk, that's hilarious tbh how the ignore this =)

**Closed** 2020-11-06 01:07 UTC
