### ISSUE TITLE
After Installing it blasted out my vscode syntax color 

### ISSUE THREAD

**Issue by Rafat97** [microsoft/TypeScript-TmLanguage#937] opened 2022-11-17 08:50 UTC
## Why did this occur? 

| Before Installing  | After Installing  |
| ----------- | ----------- |
| ![1-before](https://user-images.githubusercontent.com/21246862/202399211-74768d07-6e39-4bd1-a14b-c9bd6ad4a07d.png)  | ![2-after](https://user-images.githubusercontent.com/21246862/202399239-18e6e6e7-8669-4e3b-af99-21e6215ccdd2.png)     |

## System Info

OS: Windows 10 Pro
Node version: v16
vscode version: 1.73.1

**Comment by adabaed** [comment] 2022-11-17 13:51
Same problem here @Rafat97 😔

**Comment by sheetalkamat** [comment] 2022-11-17 19:48
Duplicate of https://github.com/microsoft/vscode-typescript-next/issues/43

**Closed by sheetalkamat** 2022-11-17 19:48 UTC
