### ISSUE TITLE
Is it possible to add accessor TM selector to square brackets in JS & TS?

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#555] opened 2017-12-22 19:14 UTC
_From @usernamehw on December 22, 2017 9:30_

Dot already have this selector: `punctuation.accessor`
```javascript
arr[0] = [0];
```
Property accessor is on the left. Array literal on the right. Now both have only `meta.array.literal`.

_Copied from original issue: Microsoft/vscode#40709_

**Comment by sheetalkamat** [comment] 2017-12-22 20:26
Is it really needed? Most of the grammars like the one in https://github.com/atom/language-javascript or the sublime's js grammar, dont distinguish between property access or array literal scoping.

**Comment by usernamehw** [comment] 2017-12-22 20:33
No.

**Comment by sheetalkamat** [comment] 2017-12-22 21:16
Then i am closing this as by design for now.

**Closed by sheetalkamat** 2017-12-22 21:16 UTC
