### ISSUE TITLE
No typescript highlighting for arrow function with line break before first param

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#539] opened 2017-11-08 18:22 UTC
_From @arznaar on November 8, 2017 17:35_

Code below compiles correctly to javascript and runs without error.

- VSCode Version: 1.17.2
- Typescript version: 2.5.3
- OS Version: Windows 10 version 1703 build 15063.540
- Reproduces without extensions: Yes

Steps to Reproduce:

Write first param for the arrow function on the next line. Example: 
```
const goodMethod = (param1: string, param2: string) => {
}

const badMethod = (
    param1: string,
    param2: string
) => {
}
```

![vscode-bug-2017-11-08t17-15-00](https://user-images.githubusercontent.com/6916413/32563975-bdf93984-c4c3-11e7-8458-bef5c835b662.PNG)

_Copied from original issue: Microsoft/vscode#37837_

**Comment by mjbvz** [comment] 2017-11-08 18:23
This is a similar issue to #481 and some others. We currently do not handle multiline arrow function declarations well

**Comment by arznaar** [comment] 2017-11-08 18:31
>We currently do not handle multiline arrow function declarations well

It still can be reproduced in case of single arrow function
![vscode-bug-2017-11-08t21-29-00](https://user-images.githubusercontent.com/6916413/32567334-07e3b922-c4cc-11e7-9166-9dde2175a41a.PNG)

**Comment by arznaar** [comment] 2017-11-08 18:32
>We currently do not handle multiline arrow function declarations well

It still can be reproduced in case of single arrow function
![vscode-bug-2017-11-08t21-29-00](https://user-images.githubusercontent.com/6916413/32567334-07e3b922-c4cc-11e7-9166-9dde2175a41a.PNG)

**Comment by arznaar** [comment] 2017-11-08 18:32
>We currently do not handle multiline arrow function declarations well

It still can be reproduced in case of single arrow function
![vscode-bug-2017-11-08t21-29-00](https://user-images.githubusercontent.com/6916413/32567334-07e3b922-c4cc-11e7-9166-9dde2175a41a.PNG)

**Comment by sheetalkamat** [comment] 2017-11-09 17:59
This is duplicate of #481 and cant be fixed because of limitation of the tmLanguage syntax not being able to lookup beyond current line

**Closed by sheetalkamat** 2017-11-09 17:59 UTC
Labels: limitation

**Comment by arznaar** [comment] 2017-11-10 07:57
It's so sad that highlighting works differently than compiler and we have such inconsistencies.

**Comment by sheetalkamat** [comment] 2018-03-06 23:19
Released [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.33 that contains #552 which should address issues reported here. After letting it bake in that extension for 2-3 weeks, I could merge #552
