### ISSUE TITLE
JS Syntax coloration breaks at generic usage

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#495] opened 2017-08-03 20:06 UTC
_From @yleflour on August 3, 2017 15:29_

- VSCode Version: 1.14.2
- OS Version: macOS Sierra - 10.12.5

Steps to Reproduce:

Please note that this is Flow typing and not Typescript typing.

1. Copy and paste [this gist](https://gist.github.com/yleflour/0f57b68d55c24ee0bf35f6e0b17fd077) in VSCode in a .js file
2. Coloration is broken at `Record<UserType>`

![image](https://user-images.githubusercontent.com/1863461/28929585-a0a484d2-7870-11e7-8974-f3a90a7763cd.png)

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#31983_

**Comment by mjbvz** [comment] 2017-08-03 20:06
Perhaps a duplicate of #481

**Comment by sheetalkamat** [comment] 2017-09-13 21:55
Duplicate of #481

**Closed by sheetalkamat** 2017-09-13 21:55 UTC
