### ISSUE TITLE
TypeScript Named Tuples cause the coloring to get messed up

### ISSUE THREAD

**Issue by Zamiell** [microsoft/TypeScript-TmLanguage#901] opened 2022-02-26 21:30 UTC
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  1.4.0

**Code**

```ts
const v = {
  room: {
    /** Indexed by grid index. */
    initializedGridEntities: new Map<
      int,
      [gridEntityType: GridEntityType, state: int]
    >(),
  },
};
```

It looks like this in VSCode:

![image](https://user-images.githubusercontent.com/5511220/155859668-d0641d16-226e-4b46-bab6-cf2dcd776e27.png)

Notice how the final characters should be white, but they are instead blue because the named tuple messes the rest of the block up.

**Comment by sheetalkamat** [comment] 2023-02-08 22:52
This is limitation of tmGrammr  `Map<` is treated as relational operator instead of type argument start because we cant lookup beyond the line.
Duplicate of #738

**Closed by sheetalkamat** 2023-02-08 22:52 UTC
