### ISSUE TITLE
Constructor should support decorators/annotations

### ISSUE THREAD

**Issue by Fank** [Microsoft/TypeScript-TmLanguage#190] opened 2016-06-21 13:49 UTC
If you align the closing constructor curly bracket the highlight will break:
![screenshot from 2016-03-14 18-28-51](https://cloud.githubusercontent.com/assets/1900106/13753340/dac591da-ea12-11e5-9d66-ec857fbaf217.png)

If you place the bracket behind the last parameter everything works fine:
![screenshot from 2016-03-14 18-29-13](https://cloud.githubusercontent.com/assets/1900106/13753398/103ee85c-ea13-11e5-9669-e3619102095b.png)

**Comment by DanielRosenwasser** [comment] 2016-07-07 07:08
Duplicate of #8.

**Closed by DanielRosenwasser** 2016-07-07 07:08 UTC
