### ISSUE TITLE
breakline changes highlighting

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript-TmLanguage#828] opened 2020-05-21 10:26 UTC
```ts
const foo = (true);
const bar = (
  true);
```
![Code_2020-05-21_12-24-28](https://user-images.githubusercontent.com/30108880/82550018-2ea4ba00-9b5e-11ea-9c87-5640d7b24e95.png)
1.45.1

**Comment by mjbvz** [comment] 2020-06-02 02:41
The issue is that `const bar = (` is identified as an arrow function.

In general, handling multiline cases like this is quite complex and not always possible without  regressing other cases, such as:

```js
const bar = (
   x
) => { ... }
```

**Comment by sheetalkamat** [comment] 2020-11-05 21:35
This is duplicate of #795: Because the parenthesis with line ending on the first line everything inside the parenthesis is treated like parameter and it defaults to that.

**Closed by sheetalkamat** 2020-11-05 21:35 UTC
