### ISSUE TITLE
Triple closing type brackets break syntax highlighting

### ISSUE THREAD

**Issue by vshab** [microsoft/TypeScript-TmLanguage#755] opened 2019-07-06 18:37 UTC
Hello!

Comming here from: https://github.com/dracula/visual-studio-code/issues/111

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.50 / latest

**Code**

```ts
export class Foo<T> {
  private x?: number;

  bar<P extends Partial<Readonly<T>>>(arg: P): void;
  bar<P extends Partial<Readonly<T>>>(arg: () => P): void {
    if (typeof arg === 'object') {
      console.log(arg);
    } else if (typeof arg === 'function') {
      console.log(arg());
    } else {
      throw new Error();
    }

    this.x = 10;
  }
}
```

How it looks (wrong):
<img width="601" alt="Screenshot 2019-07-06 at 19 55 47" src="https://user-images.githubusercontent.com/6755908/60759978-a279c900-a057-11e9-890a-f05cd4a99313.png">

How it looks with double closing type brackets (right):
<img width="563" alt="Screenshot 2019-07-06 at 19 56 04" src="https://user-images.githubusercontent.com/6755908/60759981-ab6a9a80-a057-11e9-82a8-ce4d0850b6f7.png">

**Comment by sheetalkamat** [comment] 2019-07-11 21:32
Duplicate of #744

**Closed by sheetalkamat** 2019-07-11 21:32 UTC
