### ISSUE TITLE
TypeScript wrong highlighting when using `if` within `for`

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#17] opened 2015-11-27 16:29 UTC
_From @igabesz on November 26, 2015 11:26_

TypeScript highlighter interprets `if` calls within a `for` loop as function definitions if the `if` has middle parameter and brackets. The interpretation starts failing in the `for` loop for the last parameter. 

Not the consequence of installed extensions.
Highlighting fails for other color themes as well, not only Monokai. 

```typescript
// OK
for (var i=0;; i++) {
	if (i===0) {}
}
// Partially wrong, see for loop 3rd parameter
for (let i=0; i<5; i++)
	if (i===0) {}
// Wrong
for (var i=0; i<5; i++) {
	if (i===0) {}
}
// Wrong
for (let i=0; i<5; i++) {
	if (i===0) {}
}
// Wrong
for (; i<5;) {
	if (i===0) {}
}
```

![vs-highlight-error](https://cloud.githubusercontent.com/assets/3373181/11421925/2235eca8-9438-11e5-8231-57733459fb4e.png)

_Copied from original issue: Microsoft/vscode#704_

**Comment by aeschli** [comment] 2015-11-27 16:29
_From @igabesz on November 26, 2015 11:34_

This can get really ugly for more complex cases. (Logic mostly omitted.) 
Highlighting works fine again after removing the middle parameter of the `for` cycle. 

![vs-highlight-error2](https://cloud.githubusercontent.com/assets/3373181/11422134/e370a0e2-9439-11e5-8d0c-c64350df5918.png)

**Comment by aeschli** [comment] 2015-11-27 16:29
_From @igabesz on November 26, 2015 11:56_

OK, messing with this a little more I came across that highlighting breaks if there is a `variableName<` text in the middle parameter of `for`. I think it's something with the parsing of templates. 

* Not happens if there is whitespace, e.g. `variableName <`
* Not happens for `funcCall(variable)<`
* Not the `<` operator triggers the error, `variableName<<` also works

Also the consequences are not affecting only to the `for` body, although they are more limited afterwards. 

![vs-highlight-error3](https://cloud.githubusercontent.com/assets/3373181/11422480/9959a47e-943c-11e5-809a-c7a322ef188b.png)

**Comment by aeschli** [comment] 2015-11-27 16:29
_From @egamma on November 26, 2015 14:52_

The TypeScript Sublime plugin renders this correctly. 
Should we update the textmate bundle with the one from Microsoft/TypeScript-TmLanguage.

**Comment by aeschli** [comment] 2015-11-27 16:29
I verified that we are using the latest version from https://github.com/Microsoft/TypeScript-TmLanguage.
Installing that same grammar file also in Sublime shows there is the same bug:

VS Code on the left - Sublime 3 on the right:
![image](https://cloud.githubusercontent.com/assets/6461412/11445329/8e780c40-952b-11e5-9231-6eab8a5b668f.png)

**Comment by DanielRosenwasser** [comment] 2015-11-27 18:32
@aeschli should we close this as fixed?

**Comment by aeschli** [comment] 2015-11-30 07:20
To me it looks like a bug in the grammar. Do you disagree?

**Comment by DanielRosenwasser** [comment] 2015-11-30 07:49
Sorry, I misread that last comment; I thought VSCode was not up-to-date. I guess there's been a regression, but I think this is due to the way in which we handle `<` next to an identifier. If you put spacing around it, does the problem go away?

**Comment by aeschli** [comment] 2015-11-30 08:50
Yes, with a space in front of the < things look fine.

**Comment by zhengbli** [comment] 2015-12-03 04:21
What if you have a space before your `<` sign? There is a known issue that the current grammar cannot differenciate the casting angel bracket and the less-than sign.

**Comment by aeschli** [comment] 2015-12-03 08:27
@zhengbli Space in front of the < solves the issue. You can also see this in the 3rd screenshot
![vs-highlight-error3](https://cloud.githubusercontent.com/assets/3373181/11422480/9959a47e-943c-11e5-809a-c7a322ef188b.png)

**Comment by anubmat** [comment] 2016-03-11 00:57
Duplicate #11

**Closed by anubmat** 2016-03-11 00:57 UTC
Labels: bug, duplicate
