### ISSUE TITLE
[ts] Missing syntax highlighting for async arrow functions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#172] opened 2016-05-23 14:04 UTC
_From @crystalgreen on May 11, 2016 12:5_

- VSCode Version: 1.1.0
- OS Version:Win10

Steps to Reproduce:

1. Create .ts file
2. paste `let f = async (x) => {};`

The result should be a blue `async` and a cyan colored `x`. 
When writing `let f2 = async function(x) {};` the async is colored blue.

![async-highlighting](https://cloud.githubusercontent.com/assets/16759855/15180324/217905b2-1781-11e6-9ce0-1121372e2930.png)

_Copied from original issue: Microsoft/vscode#6283_

**Comment by glen-84** [comment] 2016-08-07 21:08
Duplicate of #168.

**Comment by sheetalkamat** [comment] 2016-09-16 20:55
Fixed by #257

**Closed by sheetalkamat** 2016-09-16 20:55 UTC
