### ISSUE TITLE
Export keyword highlighted wrong in const enum

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript-TmLanguage#78] opened 2016-02-05 03:52 UTC
The export keyword is highlighted wrong below, it should be highlighted in blue?

<img width="223" alt="screen shot 2016-02-05 at 11 51 11" src="https://cloud.githubusercontent.com/assets/1324476/12837538/c79634de-cbfe-11e5-8fa9-5fe26e60631d.png">

**Comment by tinganho** [comment] 2016-02-05 05:50
Also namespaces are highlighted wrong(should be blue?).

<img width="257" alt="screen shot 2016-02-05 at 13 46 58" src="https://cloud.githubusercontent.com/assets/1324476/12839008/5b675f84-cc0f-11e5-8f96-1573b3a689e3.png">

**Comment by aeschli** [comment] 2016-02-29 13:02
duplicate of #37

**Comment by anubmat** [comment] 2016-03-15 18:51
Solved. Closing.

**Closed by anubmat** 2016-03-15 18:51 UTC
